// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: grpc/proto/salesforce.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Recipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactKey    string                 `protobuf:"bytes,1,opt,name=ContactKey,proto3" json:"ContactKey,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{0}
}

func (x *Recipient) GetContactKey() string {
	if x != nil {
		return x.ContactKey
	}
	return ""
}

func (x *Recipient) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Recipient) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	DefinitionKey string                 `protobuf:"bytes,2,opt,name=DefinitionKey,proto3" json:"DefinitionKey,omitempty"`
	UUID          string                 `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Recipient     *Recipient             `protobuf:"bytes,4,opt,name=Recipient,proto3" json:"Recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *SendEmailRequest) GetDefinitionKey() string {
	if x != nil {
		return x.DefinitionKey
	}
	return ""
}

func (x *SendEmailRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *SendEmailRequest) GetRecipient() *Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	MessageID     string                 `protobuf:"bytes,2,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{2}
}

func (x *SendEmailResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *SendEmailResponse) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *SendEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FireEventRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Brand              string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	ContactKey         string                 `protobuf:"bytes,2,opt,name=ContactKey,proto3" json:"ContactKey,omitempty"`
	EventDefinitionKey string                 `protobuf:"bytes,3,opt,name=EventDefinitionKey,proto3" json:"EventDefinitionKey,omitempty"`
	Data               *structpb.Struct       `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FireEventRequest) Reset() {
	*x = FireEventRequest{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireEventRequest) ProtoMessage() {}

func (x *FireEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireEventRequest.ProtoReflect.Descriptor instead.
func (*FireEventRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{3}
}

func (x *FireEventRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *FireEventRequest) GetContactKey() string {
	if x != nil {
		return x.ContactKey
	}
	return ""
}

func (x *FireEventRequest) GetEventDefinitionKey() string {
	if x != nil {
		return x.EventDefinitionKey
	}
	return ""
}

func (x *FireEventRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type FireEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*FireEventResponse_EventInstanceId
	//	*FireEventResponse_Response
	Result        isFireEventResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FireEventResponse) Reset() {
	*x = FireEventResponse{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireEventResponse) ProtoMessage() {}

func (x *FireEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireEventResponse.ProtoReflect.Descriptor instead.
func (*FireEventResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{4}
}

func (x *FireEventResponse) GetResult() isFireEventResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FireEventResponse) GetEventInstanceId() string {
	if x != nil {
		if x, ok := x.Result.(*FireEventResponse_EventInstanceId); ok {
			return x.EventInstanceId
		}
	}
	return ""
}

func (x *FireEventResponse) GetResponse() *DeleteSchemaResponse {
	if x != nil {
		if x, ok := x.Result.(*FireEventResponse_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isFireEventResponse_Result interface {
	isFireEventResponse_Result()
}

type FireEventResponse_EventInstanceId struct {
	EventInstanceId string `protobuf:"bytes,1,opt,name=eventInstanceId,proto3,oneof"`
}

type FireEventResponse_Response struct {
	Response *DeleteSchemaResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*FireEventResponse_EventInstanceId) isFireEventResponse_Result() {}

func (*FireEventResponse_Response) isFireEventResponse_Result() {}

type CreateSchemaRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Brand                    string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name                     string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CategoryID               int32                  `protobuf:"varint,3,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	SendableField            *string                `protobuf:"bytes,4,opt,name=SendableField,proto3,oneof" json:"SendableField,omitempty"`
	Description              *string                `protobuf:"bytes,5,opt,name=Description,proto3,oneof" json:"Description,omitempty"`
	SendableSubscriberField  *string                `protobuf:"bytes,6,opt,name=SendableSubscriberField,proto3,oneof" json:"SendableSubscriberField,omitempty"`
	CustomObjectTemplateName *string                `protobuf:"bytes,7,opt,name=CustomObjectTemplateName,proto3,oneof" json:"CustomObjectTemplateName,omitempty"`
	CustomObjectTemplateId   *string                `protobuf:"bytes,8,opt,name=CustomObjectTemplateId,proto3,oneof" json:"CustomObjectTemplateId,omitempty"`
	Fields                   []*FieldInput          `protobuf:"bytes,9,rep,name=Fields,proto3" json:"Fields,omitempty"`
	IsSendable               *bool                  `protobuf:"varint,10,opt,name=IsSendable,proto3,oneof" json:"IsSendable,omitempty"`
	IsTestable               *bool                  `protobuf:"varint,11,opt,name=IsTestable,proto3,oneof" json:"IsTestable,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateSchemaRequest) Reset() {
	*x = CreateSchemaRequest{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchemaRequest) ProtoMessage() {}

func (x *CreateSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchemaRequest.ProtoReflect.Descriptor instead.
func (*CreateSchemaRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSchemaRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSchemaRequest) GetCategoryID() int32 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *CreateSchemaRequest) GetSendableField() string {
	if x != nil && x.SendableField != nil {
		return *x.SendableField
	}
	return ""
}

func (x *CreateSchemaRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateSchemaRequest) GetSendableSubscriberField() string {
	if x != nil && x.SendableSubscriberField != nil {
		return *x.SendableSubscriberField
	}
	return ""
}

func (x *CreateSchemaRequest) GetCustomObjectTemplateName() string {
	if x != nil && x.CustomObjectTemplateName != nil {
		return *x.CustomObjectTemplateName
	}
	return ""
}

func (x *CreateSchemaRequest) GetCustomObjectTemplateId() string {
	if x != nil && x.CustomObjectTemplateId != nil {
		return *x.CustomObjectTemplateId
	}
	return ""
}

func (x *CreateSchemaRequest) GetFields() []*FieldInput {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CreateSchemaRequest) GetIsSendable() bool {
	if x != nil && x.IsSendable != nil {
		return *x.IsSendable
	}
	return false
}

func (x *CreateSchemaRequest) GetIsTestable() bool {
	if x != nil && x.IsTestable != nil {
		return *x.IsTestable
	}
	return false
}

type UpdateSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CategoryID    int32                  `protobuf:"varint,3,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	SendableField *string                `protobuf:"bytes,4,opt,name=SendableField,proto3,oneof" json:"SendableField,omitempty"`
	Fields        []*FieldInput          `protobuf:"bytes,5,rep,name=Fields,proto3" json:"Fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchemaRequest) Reset() {
	*x = UpdateSchemaRequest{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemaRequest) ProtoMessage() {}

func (x *UpdateSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchemaRequest.ProtoReflect.Descriptor instead.
func (*UpdateSchemaRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSchemaRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSchemaRequest) GetCategoryID() int32 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *UpdateSchemaRequest) GetSendableField() string {
	if x != nil && x.SendableField != nil {
		return *x.SendableField
	}
	return ""
}

func (x *UpdateSchemaRequest) GetFields() []*FieldInput {
	if x != nil {
		return x.Fields
	}
	return nil
}

type UpdateSchemaFieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Field         *FieldInput            `protobuf:"bytes,3,opt,name=Field,proto3" json:"Field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchemaFieldRequest) Reset() {
	*x = UpdateSchemaFieldRequest{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchemaFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemaFieldRequest) ProtoMessage() {}

func (x *UpdateSchemaFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchemaFieldRequest.ProtoReflect.Descriptor instead.
func (*UpdateSchemaFieldRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSchemaFieldRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateSchemaFieldRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSchemaFieldRequest) GetField() *FieldInput {
	if x != nil {
		return x.Field
	}
	return nil
}

type CreateSchemaResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key                        string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Description                string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsActive                   bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsSendable                 bool                   `protobuf:"varint,6,opt,name=is_sendable,json=isSendable,proto3" json:"is_sendable,omitempty"`
	SendableCustomObjectField  string                 `protobuf:"bytes,7,opt,name=sendable_custom_object_field,json=sendableCustomObjectField,proto3" json:"sendable_custom_object_field,omitempty"`
	SendableSubscriberField    *string                `protobuf:"bytes,8,opt,name=sendable_subscriber_field,json=sendableSubscriberField,proto3,oneof" json:"sendable_subscriber_field,omitempty"`
	IsTestable                 bool                   `protobuf:"varint,9,opt,name=is_testable,json=isTestable,proto3" json:"is_testable,omitempty"`
	CategoryId                 int32                  `protobuf:"varint,10,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	IsObjectDeletable          bool                   `protobuf:"varint,11,opt,name=is_object_deletable,json=isObjectDeletable,proto3" json:"is_object_deletable,omitempty"`
	IsFieldAdditionAllowed     bool                   `protobuf:"varint,12,opt,name=is_field_addition_allowed,json=isFieldAdditionAllowed,proto3" json:"is_field_addition_allowed,omitempty"`
	IsFieldModificationAllowed bool                   `protobuf:"varint,13,opt,name=is_field_modification_allowed,json=isFieldModificationAllowed,proto3" json:"is_field_modification_allowed,omitempty"`
	CreatedDate                string                 `protobuf:"bytes,14,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	CreatedById                int32                  `protobuf:"varint,15,opt,name=created_by_id,json=createdById,proto3" json:"created_by_id,omitempty"`
	CreatedByName              string                 `protobuf:"bytes,16,opt,name=created_by_name,json=createdByName,proto3" json:"created_by_name,omitempty"`
	ModifiedDate               string                 `protobuf:"bytes,17,opt,name=modified_date,json=modifiedDate,proto3" json:"modified_date,omitempty"`
	ModifiedById               int32                  `protobuf:"varint,18,opt,name=modified_by_id,json=modifiedById,proto3" json:"modified_by_id,omitempty"`
	ModifiedByName             string                 `protobuf:"bytes,19,opt,name=modified_by_name,json=modifiedByName,proto3" json:"modified_by_name,omitempty"`
	OwnerId                    int32                  `protobuf:"varint,20,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerName                  string                 `protobuf:"bytes,21,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	PartnerApiObjectTypeId     int32                  `protobuf:"varint,22,opt,name=partner_api_object_type_id,json=partnerApiObjectTypeId,proto3" json:"partner_api_object_type_id,omitempty"`
	PartnerApiObjectTypeName   string                 `protobuf:"bytes,23,opt,name=partner_api_object_type_name,json=partnerApiObjectTypeName,proto3" json:"partner_api_object_type_name,omitempty"`
	RowCount                   int32                  `protobuf:"varint,24,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	FieldCount                 int32                  `protobuf:"varint,25,opt,name=field_count,json=fieldCount,proto3" json:"field_count,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CreateSchemaResponse) Reset() {
	*x = CreateSchemaResponse{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchemaResponse) ProtoMessage() {}

func (x *CreateSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchemaResponse.ProtoReflect.Descriptor instead.
func (*CreateSchemaResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSchemaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSchemaResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSchemaResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateSchemaResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSchemaResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateSchemaResponse) GetIsSendable() bool {
	if x != nil {
		return x.IsSendable
	}
	return false
}

func (x *CreateSchemaResponse) GetSendableCustomObjectField() string {
	if x != nil {
		return x.SendableCustomObjectField
	}
	return ""
}

func (x *CreateSchemaResponse) GetSendableSubscriberField() string {
	if x != nil && x.SendableSubscriberField != nil {
		return *x.SendableSubscriberField
	}
	return ""
}

func (x *CreateSchemaResponse) GetIsTestable() bool {
	if x != nil {
		return x.IsTestable
	}
	return false
}

func (x *CreateSchemaResponse) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateSchemaResponse) GetIsObjectDeletable() bool {
	if x != nil {
		return x.IsObjectDeletable
	}
	return false
}

func (x *CreateSchemaResponse) GetIsFieldAdditionAllowed() bool {
	if x != nil {
		return x.IsFieldAdditionAllowed
	}
	return false
}

func (x *CreateSchemaResponse) GetIsFieldModificationAllowed() bool {
	if x != nil {
		return x.IsFieldModificationAllowed
	}
	return false
}

func (x *CreateSchemaResponse) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *CreateSchemaResponse) GetCreatedById() int32 {
	if x != nil {
		return x.CreatedById
	}
	return 0
}

func (x *CreateSchemaResponse) GetCreatedByName() string {
	if x != nil {
		return x.CreatedByName
	}
	return ""
}

func (x *CreateSchemaResponse) GetModifiedDate() string {
	if x != nil {
		return x.ModifiedDate
	}
	return ""
}

func (x *CreateSchemaResponse) GetModifiedById() int32 {
	if x != nil {
		return x.ModifiedById
	}
	return 0
}

func (x *CreateSchemaResponse) GetModifiedByName() string {
	if x != nil {
		return x.ModifiedByName
	}
	return ""
}

func (x *CreateSchemaResponse) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateSchemaResponse) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *CreateSchemaResponse) GetPartnerApiObjectTypeId() int32 {
	if x != nil {
		return x.PartnerApiObjectTypeId
	}
	return 0
}

func (x *CreateSchemaResponse) GetPartnerApiObjectTypeName() string {
	if x != nil {
		return x.PartnerApiObjectTypeName
	}
	return ""
}

func (x *CreateSchemaResponse) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *CreateSchemaResponse) GetFieldCount() int32 {
	if x != nil {
		return x.FieldCount
	}
	return 0
}

// Message representing a single field input
type FieldInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`      // Text, EmailAddress, etc.
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // Optional in Go, but always present in proto3 with default 0
	Scale         int32                  `protobuf:"varint,4,opt,name=scale,proto3" json:"scale,omitempty"`
	IsPrimaryKey  bool                   `protobuf:"varint,5,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldInput) Reset() {
	*x = FieldInput{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldInput) ProtoMessage() {}

func (x *FieldInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldInput.ProtoReflect.Descriptor instead.
func (*FieldInput) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{9}
}

func (x *FieldInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldInput) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FieldInput) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *FieldInput) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

type DataRetentionProperties struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	IsDeleteAtEndOfRetentionPeriod bool                   `protobuf:"varint,1,opt,name=isDeleteAtEndOfRetentionPeriod,proto3" json:"isDeleteAtEndOfRetentionPeriod,omitempty"`
	IsRowBasedRetention            bool                   `protobuf:"varint,2,opt,name=isRowBasedRetention,proto3" json:"isRowBasedRetention,omitempty"`
	IsResetRetentionPeriodOnImport bool                   `protobuf:"varint,3,opt,name=isResetRetentionPeriodOnImport,proto3" json:"isResetRetentionPeriodOnImport,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *DataRetentionProperties) Reset() {
	*x = DataRetentionProperties{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRetentionProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRetentionProperties) ProtoMessage() {}

func (x *DataRetentionProperties) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRetentionProperties.ProtoReflect.Descriptor instead.
func (*DataRetentionProperties) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{10}
}

func (x *DataRetentionProperties) GetIsDeleteAtEndOfRetentionPeriod() bool {
	if x != nil {
		return x.IsDeleteAtEndOfRetentionPeriod
	}
	return false
}

func (x *DataRetentionProperties) GetIsRowBasedRetention() bool {
	if x != nil {
		return x.IsRowBasedRetention
	}
	return false
}

func (x *DataRetentionProperties) GetIsResetRetentionPeriodOnImport() bool {
	if x != nil {
		return x.IsResetRetentionPeriodOnImport
	}
	return false
}

type Item struct {
	state                      protoimpl.MessageState   `protogen:"open.v1"`
	Id                         string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                       string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key                        string                   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Description                string                   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsActive                   bool                     `protobuf:"varint,5,opt,name=isActive,proto3" json:"isActive,omitempty"`
	IsSendable                 bool                     `protobuf:"varint,6,opt,name=isSendable,proto3" json:"isSendable,omitempty"`
	SendableCustomObjectField  string                   `protobuf:"bytes,7,opt,name=sendableCustomObjectField,proto3" json:"sendableCustomObjectField,omitempty"`
	SendableSubscriberField    *string                  `protobuf:"bytes,8,opt,name=sendableSubscriberField,proto3,oneof" json:"sendableSubscriberField,omitempty"`
	IsTestable                 bool                     `protobuf:"varint,9,opt,name=isTestable,proto3" json:"isTestable,omitempty"`
	CategoryId                 int32                    `protobuf:"varint,10,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	OwnerId                    int64                    `protobuf:"varint,11,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	IsObjectDeletable          bool                     `protobuf:"varint,12,opt,name=isObjectDeletable,proto3" json:"isObjectDeletable,omitempty"`
	IsFieldAdditionAllowed     bool                     `protobuf:"varint,13,opt,name=isFieldAdditionAllowed,proto3" json:"isFieldAdditionAllowed,omitempty"`
	IsFieldModificationAllowed bool                     `protobuf:"varint,14,opt,name=isFieldModificationAllowed,proto3" json:"isFieldModificationAllowed,omitempty"`
	CreatedDate                string                   `protobuf:"bytes,15,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	CreatedById                int64                    `protobuf:"varint,16,opt,name=createdById,proto3" json:"createdById,omitempty"`
	CreatedByName              string                   `protobuf:"bytes,17,opt,name=createdByName,proto3" json:"createdByName,omitempty"`
	ModifiedDate               string                   `protobuf:"bytes,18,opt,name=modifiedDate,proto3" json:"modifiedDate,omitempty"`
	ModifiedById               int64                    `protobuf:"varint,19,opt,name=modifiedById,proto3" json:"modifiedById,omitempty"`
	ModifiedByName             string                   `protobuf:"bytes,20,opt,name=modifiedByName,proto3" json:"modifiedByName,omitempty"`
	OwnerName                  string                   `protobuf:"bytes,21,opt,name=ownerName,proto3" json:"ownerName,omitempty"`
	PartnerApiObjectTypeId     int32                    `protobuf:"varint,22,opt,name=partnerApiObjectTypeId,proto3" json:"partnerApiObjectTypeId,omitempty"`
	PartnerApiObjectTypeName   string                   `protobuf:"bytes,23,opt,name=partnerApiObjectTypeName,proto3" json:"partnerApiObjectTypeName,omitempty"`
	RowCount                   int32                    `protobuf:"varint,24,opt,name=rowCount,proto3" json:"rowCount,omitempty"`
	DataRetentionProperties    *DataRetentionProperties `protobuf:"bytes,25,opt,name=dataRetentionProperties,proto3" json:"dataRetentionProperties,omitempty"`
	FieldCount                 int32                    `protobuf:"varint,26,opt,name=fieldCount,proto3" json:"fieldCount,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{11}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Item) GetIsSendable() bool {
	if x != nil {
		return x.IsSendable
	}
	return false
}

func (x *Item) GetSendableCustomObjectField() string {
	if x != nil {
		return x.SendableCustomObjectField
	}
	return ""
}

func (x *Item) GetSendableSubscriberField() string {
	if x != nil && x.SendableSubscriberField != nil {
		return *x.SendableSubscriberField
	}
	return ""
}

func (x *Item) GetIsTestable() bool {
	if x != nil {
		return x.IsTestable
	}
	return false
}

func (x *Item) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Item) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Item) GetIsObjectDeletable() bool {
	if x != nil {
		return x.IsObjectDeletable
	}
	return false
}

func (x *Item) GetIsFieldAdditionAllowed() bool {
	if x != nil {
		return x.IsFieldAdditionAllowed
	}
	return false
}

func (x *Item) GetIsFieldModificationAllowed() bool {
	if x != nil {
		return x.IsFieldModificationAllowed
	}
	return false
}

func (x *Item) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *Item) GetCreatedById() int64 {
	if x != nil {
		return x.CreatedById
	}
	return 0
}

func (x *Item) GetCreatedByName() string {
	if x != nil {
		return x.CreatedByName
	}
	return ""
}

func (x *Item) GetModifiedDate() string {
	if x != nil {
		return x.ModifiedDate
	}
	return ""
}

func (x *Item) GetModifiedById() int64 {
	if x != nil {
		return x.ModifiedById
	}
	return 0
}

func (x *Item) GetModifiedByName() string {
	if x != nil {
		return x.ModifiedByName
	}
	return ""
}

func (x *Item) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Item) GetPartnerApiObjectTypeId() int32 {
	if x != nil {
		return x.PartnerApiObjectTypeId
	}
	return 0
}

func (x *Item) GetPartnerApiObjectTypeName() string {
	if x != nil {
		return x.PartnerApiObjectTypeName
	}
	return ""
}

func (x *Item) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *Item) GetDataRetentionProperties() *DataRetentionProperties {
	if x != nil {
		return x.DataRetentionProperties
	}
	return nil
}

func (x *Item) GetFieldCount() int32 {
	if x != nil {
		return x.FieldCount
	}
	return 0
}

type Field struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ID              string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	MaskType        string                 `protobuf:"bytes,4,opt,name=MaskType,proto3" json:"MaskType,omitempty"`
	StorageType     string                 `protobuf:"bytes,5,opt,name=StorageType,proto3" json:"StorageType,omitempty"`
	Length          int32                  `protobuf:"varint,6,opt,name=Length,proto3" json:"Length,omitempty"`
	Scale           int32                  `protobuf:"varint,7,opt,name=Scale,proto3" json:"Scale,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=Description,proto3" json:"Description,omitempty"`
	Ordinal         int32                  `protobuf:"varint,9,opt,name=Ordinal,proto3" json:"Ordinal,omitempty"`
	IsNullable      bool                   `protobuf:"varint,10,opt,name=IsNullable,proto3" json:"IsNullable,omitempty"`
	IsPrimaryKey    bool                   `protobuf:"varint,11,opt,name=IsPrimaryKey,proto3" json:"IsPrimaryKey,omitempty"`
	IsActive        bool                   `protobuf:"varint,12,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	IsTemplateField bool                   `protobuf:"varint,13,opt,name=IsTemplateField,proto3" json:"IsTemplateField,omitempty"`
	IsInheritable   bool                   `protobuf:"varint,14,opt,name=IsInheritable,proto3" json:"IsInheritable,omitempty"`
	IsOverridable   bool                   `protobuf:"varint,15,opt,name=IsOverridable,proto3" json:"IsOverridable,omitempty"`
	IsHidden        bool                   `protobuf:"varint,16,opt,name=IsHidden,proto3" json:"IsHidden,omitempty"`
	IsReadOnly      bool                   `protobuf:"varint,17,opt,name=IsReadOnly,proto3" json:"IsReadOnly,omitempty"`
	MustOverride    bool                   `protobuf:"varint,18,opt,name=MustOverride,proto3" json:"MustOverride,omitempty"`
	IsSendable      bool                   `protobuf:"varint,19,opt,name=IsSendable,proto3" json:"IsSendable,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{12}
}

func (x *Field) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetMaskType() string {
	if x != nil {
		return x.MaskType
	}
	return ""
}

func (x *Field) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *Field) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Field) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Field) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Field) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *Field) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *Field) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

func (x *Field) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Field) GetIsTemplateField() bool {
	if x != nil {
		return x.IsTemplateField
	}
	return false
}

func (x *Field) GetIsInheritable() bool {
	if x != nil {
		return x.IsInheritable
	}
	return false
}

func (x *Field) GetIsOverridable() bool {
	if x != nil {
		return x.IsOverridable
	}
	return false
}

func (x *Field) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *Field) GetIsReadOnly() bool {
	if x != nil {
		return x.IsReadOnly
	}
	return false
}

func (x *Field) GetMustOverride() bool {
	if x != nil {
		return x.MustOverride
	}
	return false
}

func (x *Field) GetIsSendable() bool {
	if x != nil {
		return x.IsSendable
	}
	return false
}

type SearchSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	SchemaName    string                 `protobuf:"bytes,2,opt,name=SchemaName,proto3" json:"SchemaName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSchemaRequest) Reset() {
	*x = SearchSchemaRequest{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSchemaRequest) ProtoMessage() {}

func (x *SearchSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSchemaRequest.ProtoReflect.Descriptor instead.
func (*SearchSchemaRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{13}
}

func (x *SearchSchemaRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *SearchSchemaRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

type SearchSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Links         map[string]string      `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Items         []*Item                `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSchemaResponse) Reset() {
	*x = SearchSchemaResponse{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSchemaResponse) ProtoMessage() {}

func (x *SearchSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSchemaResponse.ProtoReflect.Descriptor instead.
func (*SearchSchemaResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{14}
}

func (x *SearchSchemaResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchSchemaResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchSchemaResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchSchemaResponse) GetLinks() map[string]string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *SearchSchemaResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type SearchSchemaIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	SchemaId      string                 `protobuf:"bytes,2,opt,name=SchemaId,proto3" json:"SchemaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSchemaIdRequest) Reset() {
	*x = SearchSchemaIdRequest{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSchemaIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSchemaIdRequest) ProtoMessage() {}

func (x *SearchSchemaIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSchemaIdRequest.ProtoReflect.Descriptor instead.
func (*SearchSchemaIdRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{15}
}

func (x *SearchSchemaIdRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *SearchSchemaIdRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

type SearchSchemaIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        []*Field               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSchemaIdResponse) Reset() {
	*x = SearchSchemaIdResponse{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSchemaIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSchemaIdResponse) ProtoMessage() {}

func (x *SearchSchemaIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSchemaIdResponse.ProtoReflect.Descriptor instead.
func (*SearchSchemaIdResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{16}
}

func (x *SearchSchemaIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchSchemaIdResponse) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DeleteSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documentation string                 `protobuf:"bytes,1,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Errorcode     int32                  `protobuf:"varint,2,opt,name=errorcode,proto3" json:"errorcode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchemaResponse) Reset() {
	*x = DeleteSchemaResponse{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemaResponse) ProtoMessage() {}

func (x *DeleteSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemaResponse.ProtoReflect.Descriptor instead.
func (*DeleteSchemaResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteSchemaResponse) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *DeleteSchemaResponse) GetErrorcode() int32 {
	if x != nil {
		return x.Errorcode
	}
	return 0
}

func (x *DeleteSchemaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InsertRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ExtensionKey  string                 `protobuf:"bytes,3,opt,name=extensionKey,proto3" json:"extensionKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRowsRequest) Reset() {
	*x = InsertRowsRequest{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRowsRequest) ProtoMessage() {}

func (x *InsertRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRowsRequest.ProtoReflect.Descriptor instead.
func (*InsertRowsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{18}
}

func (x *InsertRowsRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *InsertRowsRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InsertRowsRequest) GetExtensionKey() string {
	if x != nil {
		return x.ExtensionKey
	}
	return ""
}

type InsertRowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRowsResponse) Reset() {
	*x = InsertRowsResponse{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRowsResponse) ProtoMessage() {}

func (x *InsertRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRowsResponse.ProtoReflect.Descriptor instead.
func (*InsertRowsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{19}
}

func (x *InsertRowsResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CheckInsertRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInsertRowsRequest) Reset() {
	*x = CheckInsertRowsRequest{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInsertRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInsertRowsRequest) ProtoMessage() {}

func (x *CheckInsertRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInsertRowsRequest.ProtoReflect.Descriptor instead.
func (*CheckInsertRowsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{20}
}

func (x *CheckInsertRowsRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CheckInsertRowsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CheckInsertRowsResponseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInsertRowsResponseError) Reset() {
	*x = CheckInsertRowsResponseError{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInsertRowsResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInsertRowsResponseError) ProtoMessage() {}

func (x *CheckInsertRowsResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInsertRowsResponseError.ProtoReflect.Descriptor instead.
func (*CheckInsertRowsResponseError) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{21}
}

func (x *CheckInsertRowsResponseError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CheckInsertRowsResponseError) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckInsertRowsResponseError) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type CheckInsertRowsResponseItem struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Message       string                          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Errors        []*CheckInsertRowsResponseError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Status        string                          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode     int32                           `protobuf:"varint,4,opt,name=errorCode,proto3" json:"errorCode,omitempty"` // optional; default is 0 if not present
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInsertRowsResponseItem) Reset() {
	*x = CheckInsertRowsResponseItem{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInsertRowsResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInsertRowsResponseItem) ProtoMessage() {}

func (x *CheckInsertRowsResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInsertRowsResponseItem.ProtoReflect.Descriptor instead.
func (*CheckInsertRowsResponseItem) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{22}
}

func (x *CheckInsertRowsResponseItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckInsertRowsResponseItem) GetErrors() []*CheckInsertRowsResponseError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CheckInsertRowsResponseItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckInsertRowsResponseItem) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type CheckInsertRowsResponse struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Page           int32                           `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                           `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Count          int32                           `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Items          []*CheckInsertRowsResponseItem  `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	RequestId      string                          `protobuf:"bytes,5,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ResultMessages []*CheckInsertRowsResultMessage `protobuf:"bytes,6,rep,name=resultMessages,proto3" json:"resultMessages,omitempty"` // Adjust if resultMessages are structured
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckInsertRowsResponse) Reset() {
	*x = CheckInsertRowsResponse{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInsertRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInsertRowsResponse) ProtoMessage() {}

func (x *CheckInsertRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInsertRowsResponse.ProtoReflect.Descriptor instead.
func (*CheckInsertRowsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{23}
}

func (x *CheckInsertRowsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CheckInsertRowsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CheckInsertRowsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CheckInsertRowsResponse) GetItems() []*CheckInsertRowsResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckInsertRowsResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CheckInsertRowsResponse) GetResultMessages() []*CheckInsertRowsResultMessage {
	if x != nil {
		return x.ResultMessages
	}
	return nil
}

type CheckInsertRowsResultMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultType    string                 `protobuf:"bytes,1,opt,name=ResultType,proto3" json:"ResultType,omitempty"`
	ResultClass   string                 `protobuf:"bytes,2,opt,name=ResultClass,proto3" json:"ResultClass,omitempty"`
	ResultCode    string                 `protobuf:"bytes,3,opt,name=ResultCode,proto3" json:"ResultCode,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInsertRowsResultMessage) Reset() {
	*x = CheckInsertRowsResultMessage{}
	mi := &file_grpc_proto_salesforce_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInsertRowsResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInsertRowsResultMessage) ProtoMessage() {}

func (x *CheckInsertRowsResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_salesforce_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInsertRowsResultMessage.ProtoReflect.Descriptor instead.
func (*CheckInsertRowsResultMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_salesforce_proto_rawDescGZIP(), []int{24}
}

func (x *CheckInsertRowsResultMessage) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *CheckInsertRowsResultMessage) GetResultClass() string {
	if x != nil {
		return x.ResultClass
	}
	return ""
}

func (x *CheckInsertRowsResultMessage) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

func (x *CheckInsertRowsResultMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_proto_salesforce_proto protoreflect.FileDescriptor

const file_grpc_proto_salesforce_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpc/proto/salesforce.proto\x12\n" +
	"salesforce\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n" +
	"\tRecipient\x12\x1e\n" +
	"\n" +
	"ContactKey\x18\x01 \x01(\tR\n" +
	"ContactKey\x12\x0e\n" +
	"\x02To\x18\x02 \x01(\tR\x02To\x12E\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2%.salesforce.Recipient.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\x10SendEmailRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12$\n" +
	"\rDefinitionKey\x18\x02 \x01(\tR\rDefinitionKey\x12\x12\n" +
	"\x04UUID\x18\x03 \x01(\tR\x04UUID\x123\n" +
	"\tRecipient\x18\x04 \x01(\v2\x15.salesforce.RecipientR\tRecipient\"g\n" +
	"\x11SendEmailResponse\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x12\x1c\n" +
	"\tMessageID\x18\x02 \x01(\tR\tMessageID\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\tR\x06Status\"\xa5\x01\n" +
	"\x10FireEventRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x1e\n" +
	"\n" +
	"ContactKey\x18\x02 \x01(\tR\n" +
	"ContactKey\x12.\n" +
	"\x12EventDefinitionKey\x18\x03 \x01(\tR\x12EventDefinitionKey\x12+\n" +
	"\x04Data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04Data\"\x89\x01\n" +
	"\x11FireEventResponse\x12*\n" +
	"\x0feventInstanceId\x18\x01 \x01(\tH\x00R\x0feventInstanceId\x12>\n" +
	"\bresponse\x18\x02 \x01(\v2 .salesforce.DeleteSchemaResponseH\x00R\bresponseB\b\n" +
	"\x06result\"\xfc\x04\n" +
	"\x13CreateSchemaRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x03 \x01(\x05R\n" +
	"CategoryID\x12)\n" +
	"\rSendableField\x18\x04 \x01(\tH\x00R\rSendableField\x88\x01\x01\x12%\n" +
	"\vDescription\x18\x05 \x01(\tH\x01R\vDescription\x88\x01\x01\x12=\n" +
	"\x17SendableSubscriberField\x18\x06 \x01(\tH\x02R\x17SendableSubscriberField\x88\x01\x01\x12?\n" +
	"\x18CustomObjectTemplateName\x18\a \x01(\tH\x03R\x18CustomObjectTemplateName\x88\x01\x01\x12;\n" +
	"\x16CustomObjectTemplateId\x18\b \x01(\tH\x04R\x16CustomObjectTemplateId\x88\x01\x01\x12.\n" +
	"\x06Fields\x18\t \x03(\v2\x16.salesforce.FieldInputR\x06Fields\x12#\n" +
	"\n" +
	"IsSendable\x18\n" +
	" \x01(\bH\x05R\n" +
	"IsSendable\x88\x01\x01\x12#\n" +
	"\n" +
	"IsTestable\x18\v \x01(\bH\x06R\n" +
	"IsTestable\x88\x01\x01B\x10\n" +
	"\x0e_SendableFieldB\x0e\n" +
	"\f_DescriptionB\x1a\n" +
	"\x18_SendableSubscriberFieldB\x1b\n" +
	"\x19_CustomObjectTemplateNameB\x19\n" +
	"\x17_CustomObjectTemplateIdB\r\n" +
	"\v_IsSendableB\r\n" +
	"\v_IsTestable\"\xcc\x01\n" +
	"\x13UpdateSchemaRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x03 \x01(\x05R\n" +
	"CategoryID\x12)\n" +
	"\rSendableField\x18\x04 \x01(\tH\x00R\rSendableField\x88\x01\x01\x12.\n" +
	"\x06Fields\x18\x05 \x03(\v2\x16.salesforce.FieldInputR\x06FieldsB\x10\n" +
	"\x0e_SendableField\"n\n" +
	"\x18UpdateSchemaFieldRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12,\n" +
	"\x05Field\x18\x03 \x01(\v2\x16.salesforce.FieldInputR\x05Field\"\x94\b\n" +
	"\x14CreateSchemaResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1f\n" +
	"\vis_sendable\x18\x06 \x01(\bR\n" +
	"isSendable\x12?\n" +
	"\x1csendable_custom_object_field\x18\a \x01(\tR\x19sendableCustomObjectField\x12?\n" +
	"\x19sendable_subscriber_field\x18\b \x01(\tH\x00R\x17sendableSubscriberField\x88\x01\x01\x12\x1f\n" +
	"\vis_testable\x18\t \x01(\bR\n" +
	"isTestable\x12\x1f\n" +
	"\vcategory_id\x18\n" +
	" \x01(\x05R\n" +
	"categoryId\x12.\n" +
	"\x13is_object_deletable\x18\v \x01(\bR\x11isObjectDeletable\x129\n" +
	"\x19is_field_addition_allowed\x18\f \x01(\bR\x16isFieldAdditionAllowed\x12A\n" +
	"\x1dis_field_modification_allowed\x18\r \x01(\bR\x1aisFieldModificationAllowed\x12!\n" +
	"\fcreated_date\x18\x0e \x01(\tR\vcreatedDate\x12\"\n" +
	"\rcreated_by_id\x18\x0f \x01(\x05R\vcreatedById\x12&\n" +
	"\x0fcreated_by_name\x18\x10 \x01(\tR\rcreatedByName\x12#\n" +
	"\rmodified_date\x18\x11 \x01(\tR\fmodifiedDate\x12$\n" +
	"\x0emodified_by_id\x18\x12 \x01(\x05R\fmodifiedById\x12(\n" +
	"\x10modified_by_name\x18\x13 \x01(\tR\x0emodifiedByName\x12\x19\n" +
	"\bowner_id\x18\x14 \x01(\x05R\aownerId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x15 \x01(\tR\townerName\x12:\n" +
	"\x1apartner_api_object_type_id\x18\x16 \x01(\x05R\x16partnerApiObjectTypeId\x12>\n" +
	"\x1cpartner_api_object_type_name\x18\x17 \x01(\tR\x18partnerApiObjectTypeName\x12\x1b\n" +
	"\trow_count\x18\x18 \x01(\x05R\browCount\x12\x1f\n" +
	"\vfield_count\x18\x19 \x01(\x05R\n" +
	"fieldCountB\x1c\n" +
	"\x1a_sendable_subscriber_field\"\x88\x01\n" +
	"\n" +
	"FieldInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12\x14\n" +
	"\x05scale\x18\x04 \x01(\x05R\x05scale\x12$\n" +
	"\x0eis_primary_key\x18\x05 \x01(\bR\fisPrimaryKey\"\xdb\x01\n" +
	"\x17DataRetentionProperties\x12F\n" +
	"\x1eisDeleteAtEndOfRetentionPeriod\x18\x01 \x01(\bR\x1eisDeleteAtEndOfRetentionPeriod\x120\n" +
	"\x13isRowBasedRetention\x18\x02 \x01(\bR\x13isRowBasedRetention\x12F\n" +
	"\x1eisResetRetentionPeriodOnImport\x18\x03 \x01(\bR\x1eisResetRetentionPeriodOnImport\"\xba\b\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bisActive\x18\x05 \x01(\bR\bisActive\x12\x1e\n" +
	"\n" +
	"isSendable\x18\x06 \x01(\bR\n" +
	"isSendable\x12<\n" +
	"\x19sendableCustomObjectField\x18\a \x01(\tR\x19sendableCustomObjectField\x12=\n" +
	"\x17sendableSubscriberField\x18\b \x01(\tH\x00R\x17sendableSubscriberField\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"isTestable\x18\t \x01(\bR\n" +
	"isTestable\x12\x1e\n" +
	"\n" +
	"categoryId\x18\n" +
	" \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\aownerId\x18\v \x01(\x03R\aownerId\x12,\n" +
	"\x11isObjectDeletable\x18\f \x01(\bR\x11isObjectDeletable\x126\n" +
	"\x16isFieldAdditionAllowed\x18\r \x01(\bR\x16isFieldAdditionAllowed\x12>\n" +
	"\x1aisFieldModificationAllowed\x18\x0e \x01(\bR\x1aisFieldModificationAllowed\x12 \n" +
	"\vcreatedDate\x18\x0f \x01(\tR\vcreatedDate\x12 \n" +
	"\vcreatedById\x18\x10 \x01(\x03R\vcreatedById\x12$\n" +
	"\rcreatedByName\x18\x11 \x01(\tR\rcreatedByName\x12\"\n" +
	"\fmodifiedDate\x18\x12 \x01(\tR\fmodifiedDate\x12\"\n" +
	"\fmodifiedById\x18\x13 \x01(\x03R\fmodifiedById\x12&\n" +
	"\x0emodifiedByName\x18\x14 \x01(\tR\x0emodifiedByName\x12\x1c\n" +
	"\townerName\x18\x15 \x01(\tR\townerName\x126\n" +
	"\x16partnerApiObjectTypeId\x18\x16 \x01(\x05R\x16partnerApiObjectTypeId\x12:\n" +
	"\x18partnerApiObjectTypeName\x18\x17 \x01(\tR\x18partnerApiObjectTypeName\x12\x1a\n" +
	"\browCount\x18\x18 \x01(\x05R\browCount\x12]\n" +
	"\x17dataRetentionProperties\x18\x19 \x01(\v2#.salesforce.DataRetentionPropertiesR\x17dataRetentionProperties\x12\x1e\n" +
	"\n" +
	"fieldCount\x18\x1a \x01(\x05R\n" +
	"fieldCountB\x1a\n" +
	"\x18_sendableSubscriberField\"\xbd\x04\n" +
	"\x05Field\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\tR\x04Type\x12\x1a\n" +
	"\bMaskType\x18\x04 \x01(\tR\bMaskType\x12 \n" +
	"\vStorageType\x18\x05 \x01(\tR\vStorageType\x12\x16\n" +
	"\x06Length\x18\x06 \x01(\x05R\x06Length\x12\x14\n" +
	"\x05Scale\x18\a \x01(\x05R\x05Scale\x12 \n" +
	"\vDescription\x18\b \x01(\tR\vDescription\x12\x18\n" +
	"\aOrdinal\x18\t \x01(\x05R\aOrdinal\x12\x1e\n" +
	"\n" +
	"IsNullable\x18\n" +
	" \x01(\bR\n" +
	"IsNullable\x12\"\n" +
	"\fIsPrimaryKey\x18\v \x01(\bR\fIsPrimaryKey\x12\x1a\n" +
	"\bIsActive\x18\f \x01(\bR\bIsActive\x12(\n" +
	"\x0fIsTemplateField\x18\r \x01(\bR\x0fIsTemplateField\x12$\n" +
	"\rIsInheritable\x18\x0e \x01(\bR\rIsInheritable\x12$\n" +
	"\rIsOverridable\x18\x0f \x01(\bR\rIsOverridable\x12\x1a\n" +
	"\bIsHidden\x18\x10 \x01(\bR\bIsHidden\x12\x1e\n" +
	"\n" +
	"IsReadOnly\x18\x11 \x01(\bR\n" +
	"IsReadOnly\x12\"\n" +
	"\fMustOverride\x18\x12 \x01(\bR\fMustOverride\x12\x1e\n" +
	"\n" +
	"IsSendable\x18\x13 \x01(\bR\n" +
	"IsSendable\"K\n" +
	"\x13SearchSchemaRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x1e\n" +
	"\n" +
	"SchemaName\x18\x02 \x01(\tR\n" +
	"SchemaName\"\x81\x02\n" +
	"\x14SearchSchemaResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x12A\n" +
	"\x05links\x18\x04 \x03(\v2+.salesforce.SearchSchemaResponse.LinksEntryR\x05links\x12&\n" +
	"\x05items\x18\x05 \x03(\v2\x10.salesforce.ItemR\x05items\x1a8\n" +
	"\n" +
	"LinksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x15SearchSchemaIdRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x1a\n" +
	"\bSchemaId\x18\x02 \x01(\tR\bSchemaId\"S\n" +
	"\x16SearchSchemaIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x06fields\x18\x02 \x03(\v2\x11.salesforce.FieldR\x06fields\"t\n" +
	"\x14DeleteSchemaResponse\x12$\n" +
	"\rdocumentation\x18\x01 \x01(\tR\rdocumentation\x12\x1c\n" +
	"\terrorcode\x18\x02 \x01(\x05R\terrorcode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x80\x01\n" +
	"\x11InsertRowsRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\"\n" +
	"\fextensionKey\x18\x03 \x01(\tR\fextensionKey\"2\n" +
	"\x12InsertRowsResponse\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\"L\n" +
	"\x16CheckInsertRowsRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\tR\trequestId\"t\n" +
	"\x1cCheckInsertRowsResponseError\x12\"\n" +
	"\ferrorMessage\x18\x01 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\terrorCode\x18\x03 \x01(\x05R\terrorCode\"\xaf\x01\n" +
	"\x1bCheckInsertRowsResponseItem\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12@\n" +
	"\x06errors\x18\x02 \x03(\v2(.salesforce.CheckInsertRowsResponseErrorR\x06errors\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\terrorCode\x18\x04 \x01(\x05R\terrorCode\"\x8e\x02\n" +
	"\x17CheckInsertRowsResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12=\n" +
	"\x05items\x18\x04 \x03(\v2'.salesforce.CheckInsertRowsResponseItemR\x05items\x12\x1c\n" +
	"\trequestId\x18\x05 \x01(\tR\trequestId\x12P\n" +
	"\x0eresultMessages\x18\x06 \x03(\v2(.salesforce.CheckInsertRowsResultMessageR\x0eresultMessages\"\x9a\x01\n" +
	"\x1cCheckInsertRowsResultMessage\x12\x1e\n" +
	"\n" +
	"ResultType\x18\x01 \x01(\tR\n" +
	"ResultType\x12 \n" +
	"\vResultClass\x18\x02 \x01(\tR\vResultClass\x12\x1e\n" +
	"\n" +
	"ResultCode\x18\x03 \x01(\tR\n" +
	"ResultCode\x12\x18\n" +
	"\aMessage\x18\x04 \x01(\tR\aMessage2\x8e\t\n" +
	"\x11SalesforceService\x12j\n" +
	"\tFireEvent\x12\x1c.salesforce.FireEventRequest\x1a\x1d.salesforce.FireEventResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/{brand}/fireEvent\x12v\n" +
	"\fCreateSchema\x12\x1f.salesforce.CreateSchemaRequest\x1a .salesforce.CreateSchemaResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/{brand}/createSchema\x12\x80\x01\n" +
	"\fSearchSchema\x12\x1f.salesforce.SearchSchemaRequest\x1a .salesforce.SearchSchemaResponse\"-\x82\xd3\xe4\x93\x02'\x12%/v1/searchSchema/{brand}/{SchemaName}\x12\x86\x01\n" +
	"\x0fGetSchemaFields\x12!.salesforce.SearchSchemaIdRequest\x1a\".salesforce.SearchSchemaIdResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/schema/fields/{brand}/{SchemaId}\x12\x80\x01\n" +
	"\fDeleteSchema\x12\x1f.salesforce.SearchSchemaRequest\x1a .salesforce.DeleteSchemaResponse\"-\x82\xd3\xe4\x93\x02'*%/v1/deleteSchema/{brand}/{SchemaName}\x12~\n" +
	"\x11UpdateSchemaField\x12\x1f.salesforce.SearchSchemaRequest\x1a .salesforce.SearchSchemaResponse\"&\x82\xd3\xe4\x93\x02 2\x1e/v1/updateSchema/{brand}/field\x12\x83\x01\n" +
	"\n" +
	"InsertRows\x12\x1d.salesforce.InsertRowsRequest\x1a\x1e.salesforce.InsertRowsResponse\"6\x82\xd3\xe4\x93\x020:\apayload\"%/v1/InsertRows/{brand}/{extensionKey}\x12q\n" +
	"\tSendEmail\x12\x1c.salesforce.SendEmailRequest\x1a\x1d.salesforce.SendEmailResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/sendEmail/{brand}/{UUID}\x12\x8c\x01\n" +
	"\x0fCheckInsertRows\x12\".salesforce.CheckInsertRowsRequest\x1a#.salesforce.CheckInsertRowsResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/InsertRows/{brand}/check/{requestId}B\x15Z\x13salesforce-proto/pbb\x06proto3"

var (
	file_grpc_proto_salesforce_proto_rawDescOnce sync.Once
	file_grpc_proto_salesforce_proto_rawDescData []byte
)

func file_grpc_proto_salesforce_proto_rawDescGZIP() []byte {
	file_grpc_proto_salesforce_proto_rawDescOnce.Do(func() {
		file_grpc_proto_salesforce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_salesforce_proto_rawDesc), len(file_grpc_proto_salesforce_proto_rawDesc)))
	})
	return file_grpc_proto_salesforce_proto_rawDescData
}

var file_grpc_proto_salesforce_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_grpc_proto_salesforce_proto_goTypes = []any{
	(*Recipient)(nil),                    // 0: salesforce.Recipient
	(*SendEmailRequest)(nil),             // 1: salesforce.SendEmailRequest
	(*SendEmailResponse)(nil),            // 2: salesforce.SendEmailResponse
	(*FireEventRequest)(nil),             // 3: salesforce.FireEventRequest
	(*FireEventResponse)(nil),            // 4: salesforce.FireEventResponse
	(*CreateSchemaRequest)(nil),          // 5: salesforce.CreateSchemaRequest
	(*UpdateSchemaRequest)(nil),          // 6: salesforce.UpdateSchemaRequest
	(*UpdateSchemaFieldRequest)(nil),     // 7: salesforce.UpdateSchemaFieldRequest
	(*CreateSchemaResponse)(nil),         // 8: salesforce.CreateSchemaResponse
	(*FieldInput)(nil),                   // 9: salesforce.FieldInput
	(*DataRetentionProperties)(nil),      // 10: salesforce.DataRetentionProperties
	(*Item)(nil),                         // 11: salesforce.Item
	(*Field)(nil),                        // 12: salesforce.Field
	(*SearchSchemaRequest)(nil),          // 13: salesforce.SearchSchemaRequest
	(*SearchSchemaResponse)(nil),         // 14: salesforce.SearchSchemaResponse
	(*SearchSchemaIdRequest)(nil),        // 15: salesforce.SearchSchemaIdRequest
	(*SearchSchemaIdResponse)(nil),       // 16: salesforce.SearchSchemaIdResponse
	(*DeleteSchemaResponse)(nil),         // 17: salesforce.DeleteSchemaResponse
	(*InsertRowsRequest)(nil),            // 18: salesforce.InsertRowsRequest
	(*InsertRowsResponse)(nil),           // 19: salesforce.InsertRowsResponse
	(*CheckInsertRowsRequest)(nil),       // 20: salesforce.CheckInsertRowsRequest
	(*CheckInsertRowsResponseError)(nil), // 21: salesforce.CheckInsertRowsResponseError
	(*CheckInsertRowsResponseItem)(nil),  // 22: salesforce.CheckInsertRowsResponseItem
	(*CheckInsertRowsResponse)(nil),      // 23: salesforce.CheckInsertRowsResponse
	(*CheckInsertRowsResultMessage)(nil), // 24: salesforce.CheckInsertRowsResultMessage
	nil,                                  // 25: salesforce.Recipient.AttributesEntry
	nil,                                  // 26: salesforce.SearchSchemaResponse.LinksEntry
	(*structpb.Struct)(nil),              // 27: google.protobuf.Struct
}
var file_grpc_proto_salesforce_proto_depIdxs = []int32{
	25, // 0: salesforce.Recipient.attributes:type_name -> salesforce.Recipient.AttributesEntry
	0,  // 1: salesforce.SendEmailRequest.Recipient:type_name -> salesforce.Recipient
	27, // 2: salesforce.FireEventRequest.Data:type_name -> google.protobuf.Struct
	17, // 3: salesforce.FireEventResponse.response:type_name -> salesforce.DeleteSchemaResponse
	9,  // 4: salesforce.CreateSchemaRequest.Fields:type_name -> salesforce.FieldInput
	9,  // 5: salesforce.UpdateSchemaRequest.Fields:type_name -> salesforce.FieldInput
	9,  // 6: salesforce.UpdateSchemaFieldRequest.Field:type_name -> salesforce.FieldInput
	10, // 7: salesforce.Item.dataRetentionProperties:type_name -> salesforce.DataRetentionProperties
	26, // 8: salesforce.SearchSchemaResponse.links:type_name -> salesforce.SearchSchemaResponse.LinksEntry
	11, // 9: salesforce.SearchSchemaResponse.items:type_name -> salesforce.Item
	12, // 10: salesforce.SearchSchemaIdResponse.fields:type_name -> salesforce.Field
	27, // 11: salesforce.InsertRowsRequest.payload:type_name -> google.protobuf.Struct
	21, // 12: salesforce.CheckInsertRowsResponseItem.errors:type_name -> salesforce.CheckInsertRowsResponseError
	22, // 13: salesforce.CheckInsertRowsResponse.items:type_name -> salesforce.CheckInsertRowsResponseItem
	24, // 14: salesforce.CheckInsertRowsResponse.resultMessages:type_name -> salesforce.CheckInsertRowsResultMessage
	3,  // 15: salesforce.SalesforceService.FireEvent:input_type -> salesforce.FireEventRequest
	5,  // 16: salesforce.SalesforceService.CreateSchema:input_type -> salesforce.CreateSchemaRequest
	13, // 17: salesforce.SalesforceService.SearchSchema:input_type -> salesforce.SearchSchemaRequest
	15, // 18: salesforce.SalesforceService.GetSchemaFields:input_type -> salesforce.SearchSchemaIdRequest
	13, // 19: salesforce.SalesforceService.DeleteSchema:input_type -> salesforce.SearchSchemaRequest
	13, // 20: salesforce.SalesforceService.UpdateSchemaField:input_type -> salesforce.SearchSchemaRequest
	18, // 21: salesforce.SalesforceService.InsertRows:input_type -> salesforce.InsertRowsRequest
	1,  // 22: salesforce.SalesforceService.SendEmail:input_type -> salesforce.SendEmailRequest
	20, // 23: salesforce.SalesforceService.CheckInsertRows:input_type -> salesforce.CheckInsertRowsRequest
	4,  // 24: salesforce.SalesforceService.FireEvent:output_type -> salesforce.FireEventResponse
	8,  // 25: salesforce.SalesforceService.CreateSchema:output_type -> salesforce.CreateSchemaResponse
	14, // 26: salesforce.SalesforceService.SearchSchema:output_type -> salesforce.SearchSchemaResponse
	16, // 27: salesforce.SalesforceService.GetSchemaFields:output_type -> salesforce.SearchSchemaIdResponse
	17, // 28: salesforce.SalesforceService.DeleteSchema:output_type -> salesforce.DeleteSchemaResponse
	14, // 29: salesforce.SalesforceService.UpdateSchemaField:output_type -> salesforce.SearchSchemaResponse
	19, // 30: salesforce.SalesforceService.InsertRows:output_type -> salesforce.InsertRowsResponse
	2,  // 31: salesforce.SalesforceService.SendEmail:output_type -> salesforce.SendEmailResponse
	23, // 32: salesforce.SalesforceService.CheckInsertRows:output_type -> salesforce.CheckInsertRowsResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_grpc_proto_salesforce_proto_init() }
func file_grpc_proto_salesforce_proto_init() {
	if File_grpc_proto_salesforce_proto != nil {
		return
	}
	file_grpc_proto_salesforce_proto_msgTypes[4].OneofWrappers = []any{
		(*FireEventResponse_EventInstanceId)(nil),
		(*FireEventResponse_Response)(nil),
	}
	file_grpc_proto_salesforce_proto_msgTypes[5].OneofWrappers = []any{}
	file_grpc_proto_salesforce_proto_msgTypes[6].OneofWrappers = []any{}
	file_grpc_proto_salesforce_proto_msgTypes[8].OneofWrappers = []any{}
	file_grpc_proto_salesforce_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_salesforce_proto_rawDesc), len(file_grpc_proto_salesforce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_salesforce_proto_goTypes,
		DependencyIndexes: file_grpc_proto_salesforce_proto_depIdxs,
		MessageInfos:      file_grpc_proto_salesforce_proto_msgTypes,
	}.Build()
	File_grpc_proto_salesforce_proto = out.File
	file_grpc_proto_salesforce_proto_goTypes = nil
	file_grpc_proto_salesforce_proto_depIdxs = nil
}
